"""finalized model set-up

Revision ID: 921b9d0f6a2e
Revises: 6dc8eb59b109
Create Date: 2023-10-06 10:55:05.968676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921b9d0f6a2e'
down_revision = '6dc8eb59b109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_entries_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('task_container_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_task_assignments_task_container_id_task_containers'), 'task_containers', ['task_container_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_task_assignments_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_container_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_task_container_id_task_containers'), 'task_containers', ['task_container_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_task_container_id_task_containers'), type_='foreignkey')
        batch_op.drop_column('task_container_id')

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_assignments_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_task_assignments_task_container_id_task_containers'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('task_container_id')
        batch_op.drop_column('complete')

    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_entries_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
